#!/bin/bash

# This script merges and sorts the contents of two text files lexicographically (case-insensitive).
# Usage: ./script.sh file1.txt file2.txt

file1="$1"
file2="$2"

{ cat "$file1"; echo; cat "$file2"; } | sort -f
